name: reusable-workflow
on: 
  workflow_call:
    inputs:
      artifact-name:
        description: the name of the deployable artifact files
        required: false
        default: dist
        type: string
    secrets:
      some-secret:
        required: false
    outputs:
      result:
        description: the result of the deployment operation
        value: ${{jobs.first-job.outputs.outcome}}
        
jobs:
  first-job:
    outputs:
      outcome: ${{steps.print-output.outputs.step-result}}
    runs-on: windows-latest
    steps:
      - name: get artifact code
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifact-name}}
      - name: list files
        run: ls
      - name: output information
        run: echo 'deploying the website'
      - name: output the result
        id: print-output
        run: echo '::set-output name=step-result::success'